package Business.Entities;
// Generated 18/04/2017 09:37:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private Integer idArea;
     private String nombre;
     private String descripcion;
     private boolean estado;
     private Set subareas = new HashSet(0);
     private Set tiposervicios = new HashSet(0);

    public Area() {
    }

	
    public Area(String nombre, boolean estado) {
        this.nombre = nombre;
        this.estado = estado;
    }
    public Area(String nombre, String descripcion, boolean estado, Set subareas, Set tiposervicios) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.estado = estado;
       this.subareas = subareas;
       this.tiposervicios = tiposervicios;
    }
   
    public Integer getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(Integer idArea) {
        this.idArea = idArea;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getSubareas() {
        return this.subareas;
    }
    
    public void setSubareas(Set subareas) {
        this.subareas = subareas;
    }
    public Set getTiposervicios() {
        return this.tiposervicios;
    }
    
    public void setTiposervicios(Set tiposervicios) {
        this.tiposervicios = tiposervicios;
    }




}


