package Business.Entities;
// Generated 18/04/2017 09:37:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private Integer idEmpresa;
     private String nombre;
     private int rut;
     private String descripcion;
     private boolean estado;
     private Set servicios = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(String nombre, int rut, boolean estado) {
        this.nombre = nombre;
        this.rut = rut;
        this.estado = estado;
    }
    public Empresa(String nombre, int rut, String descripcion, boolean estado, Set servicios, Set usuarios) {
       this.nombre = nombre;
       this.rut = rut;
       this.descripcion = descripcion;
       this.estado = estado;
       this.servicios = servicios;
       this.usuarios = usuarios;
    }
   
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getRut() {
        return this.rut;
    }
    
    public void setRut(int rut) {
        this.rut = rut;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set servicios) {
        this.servicios = servicios;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


