package Business.Entities;
// Generated 18/04/2017 09:37:33 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Historialservicio generated by hbm2java
 */
public class Historialservicio  implements java.io.Serializable {


     private Long idHistorialServicio;
     private Servicio servicio;
     private String descripcion;
     private Short estado;
     private Date fechaModificacion;
     private Integer idTipoServicio;
     private Date fechaIngreso;
     private String observaciones;

    public Historialservicio() {
    }

    public Historialservicio(Servicio servicio, String descripcion, Short estado, Date fechaModificacion, Integer idTipoServicio, Date fechaIngreso, String observaciones) {
       this.servicio = servicio;
       this.descripcion = descripcion;
       this.estado = estado;
       this.fechaModificacion = fechaModificacion;
       this.idTipoServicio = idTipoServicio;
       this.fechaIngreso = fechaIngreso;
       this.observaciones = observaciones;
    }
   
    public Long getIdHistorialServicio() {
        return this.idHistorialServicio;
    }
    
    public void setIdHistorialServicio(Long idHistorialServicio) {
        this.idHistorialServicio = idHistorialServicio;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Short getEstado() {
        return this.estado;
    }
    
    public void setEstado(Short estado) {
        this.estado = estado;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Integer getIdTipoServicio() {
        return this.idTipoServicio;
    }
    
    public void setIdTipoServicio(Integer idTipoServicio) {
        this.idTipoServicio = idTipoServicio;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


