package Business.Entities;
// Generated 18/04/2017 09:37:33 by Hibernate Tools 4.3.1



/**
 * Notificaciones generated by hbm2java
 */
public class Notificaciones  implements java.io.Serializable {


     private Long idNotificaciones;
     private String asunto;
     private String mensaje;
     private String correo;
     private String enviado;

    public Notificaciones() {
    }

	
    public Notificaciones(String correo, String enviado) {
        this.correo = correo;
        this.enviado = enviado;
    }
    public Notificaciones(String asunto, String mensaje, String correo, String enviado) {
       this.asunto = asunto;
       this.mensaje = mensaje;
       this.correo = correo;
       this.enviado = enviado;
    }
   
    public Long getIdNotificaciones() {
        return this.idNotificaciones;
    }
    
    public void setIdNotificaciones(Long idNotificaciones) {
        this.idNotificaciones = idNotificaciones;
    }
    public String getAsunto() {
        return this.asunto;
    }
    
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getEnviado() {
        return this.enviado;
    }
    
    public void setEnviado(String enviado) {
        this.enviado = enviado;
    }




}


