package Business.Entities;
// Generated 18/04/2017 09:37:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Permiso generated by hbm2java
 */
public class Permiso  implements java.io.Serializable {


     private Integer idPermiso;
     private String nombreUnico;
     private String nombre;
     private boolean estado;
     private String url;
     private String descripcion;
     private Set rols = new HashSet(0);

    public Permiso() {
    }

	
    public Permiso(String nombreUnico, String nombre, boolean estado) {
        this.nombreUnico = nombreUnico;
        this.nombre = nombre;
        this.estado = estado;
    }
    public Permiso(String nombreUnico, String nombre, boolean estado, String url, String descripcion, Set rols) {
       this.nombreUnico = nombreUnico;
       this.nombre = nombre;
       this.estado = estado;
       this.url = url;
       this.descripcion = descripcion;
       this.rols = rols;
    }
   
    public Integer getIdPermiso() {
        return this.idPermiso;
    }
    
    public void setIdPermiso(Integer idPermiso) {
        this.idPermiso = idPermiso;
    }
    public String getNombreUnico() {
        return this.nombreUnico;
    }
    
    public void setNombreUnico(String nombreUnico) {
        this.nombreUnico = nombreUnico;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getRols() {
        return this.rols;
    }
    
    public void setRols(Set rols) {
        this.rols = rols;
    }




}


