package Business.Entities;
// Generated 18/04/2017 09:37:33 by Hibernate Tools 4.3.1



/**
 * Serviciosolicitante generated by hbm2java
 */
public class Serviciosolicitante  implements java.io.Serializable {


     private Long idServicioSolicitante;
     private Servicio servicio;
     private Usuario usuario;
     private String nroIdentidad;
     private Integer tipoIdentidad;
     private String telefono;
     private String nombreSolicitante;
     private String correoSolicitante;

    public Serviciosolicitante() {
    }

	
    public Serviciosolicitante(Servicio servicio) {
        this.servicio = servicio;
    }
    public Serviciosolicitante(Servicio servicio, Usuario usuario, String nroIdentidad, Integer tipoIdentidad, String telefono, String nombreSolicitante, String correoSolicitante) {
       this.servicio = servicio;
       this.usuario = usuario;
       this.nroIdentidad = nroIdentidad;
       this.tipoIdentidad = tipoIdentidad;
       this.telefono = telefono;
       this.nombreSolicitante = nombreSolicitante;
       this.correoSolicitante = correoSolicitante;
    }
   
    public Long getIdServicioSolicitante() {
        return this.idServicioSolicitante;
    }
    
    public void setIdServicioSolicitante(Long idServicioSolicitante) {
        this.idServicioSolicitante = idServicioSolicitante;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNroIdentidad() {
        return this.nroIdentidad;
    }
    
    public void setNroIdentidad(String nroIdentidad) {
        this.nroIdentidad = nroIdentidad;
    }
    public Integer getTipoIdentidad() {
        return this.tipoIdentidad;
    }
    
    public void setTipoIdentidad(Integer tipoIdentidad) {
        this.tipoIdentidad = tipoIdentidad;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getNombreSolicitante() {
        return this.nombreSolicitante;
    }
    
    public void setNombreSolicitante(String nombreSolicitante) {
        this.nombreSolicitante = nombreSolicitante;
    }
    public String getCorreoSolicitante() {
        return this.correoSolicitante;
    }
    
    public void setCorreoSolicitante(String correoSolicitante) {
        this.correoSolicitante = correoSolicitante;
    }




}


