package Business.Entities;
// Generated 18/04/2017 09:37:33 by Hibernate Tools 4.3.1



/**
 * SubareaId generated by hbm2java
 */
public class SubareaId  implements java.io.Serializable {


     private int idSubArea;
     private int idArea;

    public SubareaId() {
    }

    public SubareaId(int idSubArea, int idArea) {
       this.idSubArea = idSubArea;
       this.idArea = idArea;
    }
   
    public int getIdSubArea() {
        return this.idSubArea;
    }
    
    public void setIdSubArea(int idSubArea) {
        this.idSubArea = idSubArea;
    }
    public int getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(int idArea) {
        this.idArea = idArea;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SubareaId) ) return false;
		 SubareaId castOther = ( SubareaId ) other; 
         
		 return (this.getIdSubArea()==castOther.getIdSubArea())
 && (this.getIdArea()==castOther.getIdArea());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdSubArea();
         result = 37 * result + this.getIdArea();
         return result;
   }   


}


