package Business.Entities;
// Generated 18/04/2017 09:37:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Supervisor generated by hbm2java
 */
public class Supervisor  implements java.io.Serializable {


     private Integer idSupervisor;
     private String nombre;
     private String apellido;
     private boolean estado;
     private Set servicios = new HashSet(0);

    public Supervisor() {
    }

	
    public Supervisor(String nombre, String apellido, boolean estado) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.estado = estado;
    }
    public Supervisor(String nombre, String apellido, boolean estado, Set servicios) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.estado = estado;
       this.servicios = servicios;
    }
   
    public Integer getIdSupervisor() {
        return this.idSupervisor;
    }
    
    public void setIdSupervisor(Integer idSupervisor) {
        this.idSupervisor = idSupervisor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set servicios) {
        this.servicios = servicios;
    }




}


