package Business.Entities;
// Generated 18/04/2017 09:37:33 by Hibernate Tools 4.3.1



/**
 * TipodetalleId generated by hbm2java
 */
public class TipodetalleId  implements java.io.Serializable {


     private int idTipoDetalle;
     private int idTipo;

    public TipodetalleId() {
    }

    public TipodetalleId(int idTipoDetalle, int idTipo) {
       this.idTipoDetalle = idTipoDetalle;
       this.idTipo = idTipo;
    }
   
    public int getIdTipoDetalle() {
        return this.idTipoDetalle;
    }
    
    public void setIdTipoDetalle(int idTipoDetalle) {
        this.idTipoDetalle = idTipoDetalle;
    }
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TipodetalleId) ) return false;
		 TipodetalleId castOther = ( TipodetalleId ) other; 
         
		 return (this.getIdTipoDetalle()==castOther.getIdTipoDetalle())
 && (this.getIdTipo()==castOther.getIdTipo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTipoDetalle();
         result = 37 * result + this.getIdTipo();
         return result;
   }   


}


