package Business.Entities;
// Generated 18/04/2017 09:37:33 by Hibernate Tools 4.3.1



/**
 * Tipodetalle generated by hbm2java
 */
public class Tipodetalle  implements java.io.Serializable {


     private TipodetalleId id;
     private Tipo tipo;
     private String nombre;
     private String descripcion;

    public Tipodetalle() {
    }

	
    public Tipodetalle(TipodetalleId id, Tipo tipo, String nombre) {
        this.id = id;
        this.tipo = tipo;
        this.nombre = nombre;
    }
    public Tipodetalle(TipodetalleId id, Tipo tipo, String nombre, String descripcion) {
       this.id = id;
       this.tipo = tipo;
       this.nombre = nombre;
       this.descripcion = descripcion;
    }
   
    public TipodetalleId getId() {
        return this.id;
    }
    
    public void setId(TipodetalleId id) {
        this.id = id;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


