package Business.Entities;
// Generated 18/04/2017 09:37:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ubicacionservicio generated by hbm2java
 */
public class Ubicacionservicio  implements java.io.Serializable {


     private Integer idUbicacion;
     private Barrio barrio;
     private Float latitud;
     private String calle;
     private String nroPuerta;
     private String apto;
     private String entreCalles;
     private String nroManzana;
     private String nroSolar;
     private String nroPadron;
     private Float longitud;
     private Set servicios = new HashSet(0);

    public Ubicacionservicio() {
    }

    public Ubicacionservicio(Barrio barrio, Float latitud, String calle, String nroPuerta, String apto, String entreCalles, String nroManzana, String nroSolar, String nroPadron, Float longitud, Set servicios) {
       this.barrio = barrio;
       this.latitud = latitud;
       this.calle = calle;
       this.nroPuerta = nroPuerta;
       this.apto = apto;
       this.entreCalles = entreCalles;
       this.nroManzana = nroManzana;
       this.nroSolar = nroSolar;
       this.nroPadron = nroPadron;
       this.longitud = longitud;
       this.servicios = servicios;
    }
   
    public Integer getIdUbicacion() {
        return this.idUbicacion;
    }
    
    public void setIdUbicacion(Integer idUbicacion) {
        this.idUbicacion = idUbicacion;
    }
    public Barrio getBarrio() {
        return this.barrio;
    }
    
    public void setBarrio(Barrio barrio) {
        this.barrio = barrio;
    }
    public Float getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Float latitud) {
        this.latitud = latitud;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getNroPuerta() {
        return this.nroPuerta;
    }
    
    public void setNroPuerta(String nroPuerta) {
        this.nroPuerta = nroPuerta;
    }
    public String getApto() {
        return this.apto;
    }
    
    public void setApto(String apto) {
        this.apto = apto;
    }
    public String getEntreCalles() {
        return this.entreCalles;
    }
    
    public void setEntreCalles(String entreCalles) {
        this.entreCalles = entreCalles;
    }
    public String getNroManzana() {
        return this.nroManzana;
    }
    
    public void setNroManzana(String nroManzana) {
        this.nroManzana = nroManzana;
    }
    public String getNroSolar() {
        return this.nroSolar;
    }
    
    public void setNroSolar(String nroSolar) {
        this.nroSolar = nroSolar;
    }
    public String getNroPadron() {
        return this.nroPadron;
    }
    
    public void setNroPadron(String nroPadron) {
        this.nroPadron = nroPadron;
    }
    public Float getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Float longitud) {
        this.longitud = longitud;
    }
    public Set getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set servicios) {
        this.servicios = servicios;
    }




}


