package Business.Entities;
// Generated 18/04/2017 09:37:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Rol rol;
     private String nombre;
     private String apellido;
     private String nickname;
     private String password;
     private String token;
     private String correo;
     private boolean estado;
     private String nroIdentidad;
     private Integer tipoIdentidad;
     private String telefono;
     private Boolean notificar;
     private Set serviciosolicitantes = new HashSet(0);
     private Set empresas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(Rol rol, String nombre, String apellido, String nickname, String password, boolean estado) {
        this.rol = rol;
        this.nombre = nombre;
        this.apellido = apellido;
        this.nickname = nickname;
        this.password = password;
        this.estado = estado;
    }
    public Usuario(Rol rol, String nombre, String apellido, String nickname, String password, String token, String correo, boolean estado, String nroIdentidad, Integer tipoIdentidad, String telefono, Boolean notificar, Set serviciosolicitantes, Set empresas) {
       this.rol = rol;
       this.nombre = nombre;
       this.apellido = apellido;
       this.nickname = nickname;
       this.password = password;
       this.token = token;
       this.correo = correo;
       this.estado = estado;
       this.nroIdentidad = nroIdentidad;
       this.tipoIdentidad = tipoIdentidad;
       this.telefono = telefono;
       this.notificar = notificar;
       this.serviciosolicitantes = serviciosolicitantes;
       this.empresas = empresas;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public String getNroIdentidad() {
        return this.nroIdentidad;
    }
    
    public void setNroIdentidad(String nroIdentidad) {
        this.nroIdentidad = nroIdentidad;
    }
    public Integer getTipoIdentidad() {
        return this.tipoIdentidad;
    }
    
    public void setTipoIdentidad(Integer tipoIdentidad) {
        this.tipoIdentidad = tipoIdentidad;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Boolean getNotificar() {
        return this.notificar;
    }
    
    public void setNotificar(Boolean notificar) {
        this.notificar = notificar;
    }
    public Set getServiciosolicitantes() {
        return this.serviciosolicitantes;
    }
    
    public void setServiciosolicitantes(Set serviciosolicitantes) {
        this.serviciosolicitantes = serviciosolicitantes;
    }
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }




}


